CP DF ALS changes for CP LT
ValeevGroup/BTAS pull request #118
Opened 2021-05-17 14:02 UTC by kmp5VT

Allow one to access the CP factors optimized before the CP DF ALS computation and allow the the user to input an epsilon for these initial component factorizations

2021-05-25 13:33 UTC, evaleev requested changes

2021-05-25 13:33 UTC, evaleev commented on btas/generic/cp_df_als.h
> +                            bool calculate_epsilon = false, bool direct = true, double cp3_precision = 1e-2) {
need dox

2021-05-25 13:33 UTC, evaleev commented on btas/generic/cp_df_als.h
> +          A.push_back(init_factors_right[i]);
can move `init_factors_right[I]`?

2021-06-18 19:14 UTC, evaleev commented
@kmp5VT is this ready?

2021-06-18 19:24 UTC, kmp5VT commented
> @kmp5VT is this ready?
I am fixing your requested changes and then it will be ready

2021-07-14 15:48 UTC, kmp5VT commented
@evaleev This PR is ready to be pushed and integrated into TA

2021-07-21 17:09 UTC, merged